### ISSUE TITLE
Basic examples to make and accept calls

### ISSUE THREAD

**Issue by csimlinger** [cwysong85/sipjs-udp#16]
Hi,

I am new to SIP and was looking into your library, as Placetel only supports SIP over UDP.
Now I wanted to get started and were looking for a simple example to initiate a call / to answer incoming calls.

Any hint how I can get started? The examples in this project seem to do different things than what I imagine.

Thanks a lot!

**Comment by cwysong85** [comment]
I just published this repo here: https://github.com/cwysong85/sip.js-udp-example

I would implore you to utilize that example repo code instead of this repo because this repo utilizes a very old version of SIP.js stack and the example repo above utilizes the official SIP.js stack.  This repo will be deprecated soon since SIP.js new stack allows the transport class to be implemented with any kind of transport protocol. 

If you have any questions, please feel free to ask!

**Comment by csimlinger** [comment]
Highly appreciate your help, thanks.
I posted a comment in the linked repo with a question.
